### ISSUE TITLE
pip3 install python-dbus fails

### ISSUE THREAD

**Issue by larsimmisch** [hmvp/python-tdbus#12]
On a recent Ubuntu machine, installing python-dbus using pip3 fails. (Installation using pip2 works)

```
uname -a
Linux ohm-ubu 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
Collecting python-tdbus
  Downloading python-tdbus-0.9.tar.gz
Requirement already satisfied (use --upgrade to upgrade): gevent>=1.0 in /usr/local/lib/python3.5/dist-packages (from python-tdbus)
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.9 in /usr/local/lib/python3.5/dist-packages (from gevent>=1.0->python-tdbus)
Installing collected packages: python-tdbus
  Running setup.py install for python-tdbus ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-i_y36e2x/python-tdbus/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-91cej0x2-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/tdbus
    copying lib/tdbus/connection.py -> build/lib.linux-x86_64-3.5/tdbus
    copying lib/tdbus/__init__.py -> build/lib.linux-x86_64-3.5/tdbus
    copying lib/tdbus/handler.py -> build/lib.linux-x86_64-3.5/tdbus
    copying lib/tdbus/select.py -> build/lib.linux-x86_64-3.5/tdbus
    copying lib/tdbus/loop.py -> build/lib.linux-x86_64-3.5/tdbus
    copying lib/tdbus/gevent.py -> build/lib.linux-x86_64-3.5/tdbus
    creating build/lib.linux-x86_64-3.5/tdbus/test
    copying lib/tdbus/test/__init__.py -> build/lib.linux-x86_64-3.5/tdbus/test
    copying lib/tdbus/test/base.py -> build/lib.linux-x86_64-3.5/tdbus/test
    copying lib/tdbus/test/test_connection.py -> build/lib.linux-x86_64-3.5/tdbus/test
    copying lib/tdbus/test/test_message.py -> build/lib.linux-x86_64-3.5/tdbus/test
    running build_ext
    building 'tdbus._tdbus' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/lib
    creating build/temp.linux-x86_64-3.5/lib/tdbus
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-i_y36e2x/python-tdbus/setup.py", line 46, in <module>
        **version_info
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 49, in run
        _build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 174, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 89, in _spawn_posix
        log.info(' '.join(cmd))
    TypeError: sequence item 20: expected str instance, bytes found
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-i_y36e2x/python-tdbus/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-91cej0x2-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-i_y36e2x/python-tdbus/
```

**Comment by hmvp** [comment]
Should be solved in 0.10. That includes python3 support that was not available before
