### ISSUE TITLE
Seems to be not working in virtualenvironments

### ISSUE THREAD

**Issue by AIIX** [hmvp/python-tdbus#15]
pip install python-tdbus

Collecting python-tdbus
  Downloading python-tdbus-0.11.tar.gz
    Complete output from command python setup.py egg_info:
    Package dbus-1 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `dbus-1.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'dbus-1' found
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-wXjR8p/python-tdbus/setup.py", line 44, in <module>
        extra_compile_args=pkgconfig('--cflags', 'dbus-1'),
      File "/tmp/pip-build-wXjR8p/python-tdbus/setup.py", line 36, in pkgconfig
        output = subprocess.check_output(['pkg-config'] + list(args), universal_newlines=True)
      File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['pkg-config', '--cflags', 'dbus-1']' returned non-zero exit status 1

**Comment by AIIX** [comment]
my bad - was missing libdbus dev
